### ISSUE TITLE
Loot when player kill

### ISSUE THREAD

**Issue by plagoutte** [jascotty2/CookieMinion#1]
Hello, 

I defined a player reward as below : 
```
rewards:
    PLAYER:
        loot:
        - GOLD_NUGGET
```

No error at reload or when a player is killed, but the killer doesn't receive the reward. 

The plugin works great with monsters.

Thank you in advance
